name: test-build

on:
  schedule:
    # twice per week to preserve the cache
    - cron: "0 0 * * 1,4"
  workflow_dispatch:

jobs:
  server-docker:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: src
          cache-from: type=gha
